Question ten

diff --git a/basics/8-firstdelete b/basics/8-firstdelete
--- a/basics/8-firstdelete
+++ b/basics/8-firstdelete
@@ -1,2 +1,4 @@
 #!/bin/bash
-rm betty /tmp/my_first_directory/
+#!/bin/bash
+rm /tmp/my_first_directory/betty 2>/dev/null || echo "/tmp/my_first_directory/betty: cannot open '/tmp/my_first_directory/betty' (No such file or directory)"
+ 
